version: '3'

services:
  pi-dw-bi-5-period-mysql:
    container_name: pi-dw-bi-5-period-mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
      MYSQL_DATABASE: ${DATABASE_NAME}
    image: mysql:5.7
    ports:
      - ${DATABASE_PORT:-3306}:3306
    volumes:
      - pi-dw-bi-5-period-mysql-volume:/var/lib/mysql
    networks:
      - pi-dw-bi-5-period-network

volumes:
  pi-dw-bi-5-period-mysql-volume:
    driver: local

networks:
  pi-dw-bi-5-period-network:
    external: true
    name: pi-dw-bi-5-period-network
    driver: bridge